### ISSUE TITLE
Smuxi fails to build on Debian bookworm using dpkg-buildpackage

### ISSUE THREAD

**Issue by jeremyp3** [meebey/smuxi#295]
after seeing the release of smuxi v1.2.1, I was very happy to try it on my debian, the problem is that the debian folder doesn't seem to support debian BookWorm yetn 

I build successfully using ./autogen.sh && ./configure && make

On the other hand, when I use dpkg-buildpackage, I get an error on obsolete stuff:
"./Views/Chats/ChatView.cs(537,41): warning CS0618: `Smuxi.Engine.ChatModel.Messages' is obsolete: `Use ChatModel.MessageBuffer instead.'"

I attach the output of my build 
[output-build-smuxi.txt](https://github.com/meebey/smuxi/files/11410573/output-build-smuxi.txt)

thanks !

Jeremyp3

**Comment by meebey** [comment]
Thank you for reporting this build issue. The CI builds are not catching this problem.

    ./Frontend.cs(192,69): error CS0234: The type or namespace name `RuntimeInformation' does not exist in the namespace `System.Runtime.InteropServices'. Are you missing an assembly reference?

Looks like a build regression that was introduced by the .NET runtime detection in https://github.com/meebey/smuxi/commit/f4f37c70bac1506d590d74b7582b482dff8a3ec6

Please upload the output of a `./configure` run so I can add appropriate Mono version checks before using `RuntimeInformation`.

**Comment by jeremyp3** [comment]
I don't know if I understood what you want
[configure.txt](https://github.com/meebey/smuxi/files/11410785/configure.txt)

**Comment by jeremyp3** [comment]
I take this opportunity to add the mono packages that are installed
[dpkg-mono.txt](https://github.com/meebey/smuxi/files/11410793/dpkg-mono.txt)

**Comment by meebey** [comment]
These 2 are exactly what I needed to triage the problem. So Mono 6.8 doesn't provide the RuntimeInformation type.
The CI build with Mono 6.12 works, so the fix will be to only call RuntimeInformation if Mono >= 6.12. I will make a patch for this.

If you don't want to wait you can just comment the line 199 and 200 in [src/Frontend-GNOME/Frontend.cs](https://github.com/meebey/smuxi/commit/f4f37c70bac1506d590d74b7582b482dff8a3ec6#diff-197a3ddb5d2a0dad47798f79bc751053026ff97d4c256a63114a7103d942da41) and you should get Smuxi 1.2.1 compiled on your Debian system.

**Comment by jeremyp3** [comment]
on the other hand, what makes me question, as I said in my first post, is that if I don't try to make a debian package, I can compile smuxi 1.2.1. it's just with the debian package that I have this error.

**Comment by meebey** [comment]
Thanks for clarifying that. I thought it always failed on Debian Bookworm, regardless of how trying to build it.
So dpkg-buildpackage fails while ./configure && make works.

In that case, please upload the full output of dpkg-buildpackage. Your output-build-smuxi.txt file seem to be only the output of a "make" run, so I focused on that.

**Comment by jeremyp3** [comment]
I'm sorry I sent the wrong thing
to clean everything, I did a make clean && make distclean. 
then I made a dpkg-buildpackage -b -us -uc and here is the output
[dpkg-buildpackage-smuxi.txt](https://github.com/meebey/smuxi/files/11410846/dpkg-buildpackage-smuxi.txt)

**Comment by meebey** [comment]
I pushed a commit that should fix the problem. Please try dpkg-buildpackage from this branch: https://github.com/meebey/smuxi/tree/debian_fix

**Comment by jeremyp3** [comment]
it still doesn't work, but it seems to go further
make clean && make distclean
dpkg-buildpackage -b -us -uc
[dpkg-buildpackage-branch-debian_fix.txt](https://github.com/meebey/smuxi/files/11411024/dpkg-buildpackage-branch-debian_fix.txt)

**Comment by meebey** [comment]
@jeremyp3 I could reproduce your build error on Debian. If you try the https://github.com/meebey/smuxi/tree/debian_ci branch it should now build for you.

**Comment by jeremyp3** [comment]
I confirm that it works!
 
thanks !
